[CmdletBinding()]
param(
  [string]$Destination = '[quokkacad]',
  [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'

function Resolve-FullPath {
  param([string]$Path, [string]$BasePath)
  if ([string]::IsNullOrWhiteSpace($Path)) {
    throw 'Path is required.'
  }
  if ([System.IO.Path]::IsPathRooted($Path)) {
    return [System.IO.Path]::GetFullPath($Path)
  }
  return [System.IO.Path]::GetFullPath((Join-Path $BasePath $Path))
}

function Invoke-CheckedCommand {
  param(
    [Parameter(Mandatory = $true)][string]$FilePath,
    [string[]]$ArgumentList = @(),
    [Parameter(Mandatory = $true)][string]$WorkingDirectory,
    [string]$Label = $FilePath
  )

  Write-Host "==> $Label" -ForegroundColor Cyan
  Push-Location $WorkingDirectory
  try {
    & $FilePath @ArgumentList
    if ($LASTEXITCODE -ne 0) {
      throw "$Label failed with exit code $LASTEXITCODE"
    }
  } finally {
    Pop-Location
  }
}

function Sync-Directory {
  param(
    [Parameter(Mandatory = $true)][string]$Source,
    [Parameter(Mandatory = $true)][string]$Destination,
    [string[]]$ExcludeDirectories = @()
  )

  if (-not (Test-Path -LiteralPath $Source)) {
    throw "Source directory not found: $Source"
  }

  [System.IO.Directory]::CreateDirectory($Destination) | Out-Null

  $args = @(
    $Source,
    $Destination,
    '/MIR',
    '/FFT',
    '/R:2',
    '/W:1',
    '/NFL',
    '/NDL',
    '/NJH',
    '/NJS',
    '/NP'
  )

  if ($ExcludeDirectories -and $ExcludeDirectories.Count -gt 0) {
    $args += '/XD'
    $args += $ExcludeDirectories
  }

  Write-Host ("==> Sync {0} -> {1}" -f $Source, $Destination) -ForegroundColor Cyan
  & robocopy @args | Out-Null
  $code = $LASTEXITCODE
  if ($code -gt 7) {
    throw "robocopy failed for '$Source' -> '$Destination' (exit code $code)"
  }
}

function Ensure-NpmBuild {
  param(
    [Parameter(Mandatory = $true)][string]$ProjectPath,
    [Parameter(Mandatory = $true)][string]$ProjectLabel
  )

  if (-not (Test-Path (Join-Path $ProjectPath 'package.json'))) {
    throw "package.json not found in $ProjectPath"
  }

  if (-not (Test-Path (Join-Path $ProjectPath 'node_modules'))) {
    Invoke-CheckedCommand -FilePath 'npm' -ArgumentList @('ci') -WorkingDirectory $ProjectPath -Label "$ProjectLabel npm ci"
  }

  Invoke-CheckedCommand -FilePath 'npm' -ArgumentList @('run', 'build') -WorkingDirectory $ProjectPath -Label "$ProjectLabel build"
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Resolve-FullPath -Path '..\..' -BasePath $scriptDir
$outputRoot = Resolve-FullPath -Path $Destination -BasePath $repoRoot

$cadBridgeSource = Join-Path $repoRoot 'server\fivem-resource'
$vicroadsSource = Join-Path $repoRoot 'npwd_vicroads'
$finesVicSource = Join-Path $repoRoot 'npwd_fines_victoria'

if (-not $SkipBuild) {
  Ensure-NpmBuild -ProjectPath $vicroadsSource -ProjectLabel 'npwd_vicroads'
  Ensure-NpmBuild -ProjectPath $finesVicSource -ProjectLabel 'npwd_fines_victoria'
}

# Keep cad_bridge-hosted legacy NPWD remotes in sync with the standalone app builds.
$legacyVicRoadsDist = Join-Path $cadBridgeSource 'web\dist'
$legacyFinesVicDist = Join-Path $cadBridgeSource 'web\finesvic-dist'
$vicroadsDist = Join-Path $vicroadsSource 'web\dist'
$finesVicDist = Join-Path $finesVicSource 'web\dist'

if (Test-Path -LiteralPath $vicroadsDist) {
  Sync-Directory -Source $vicroadsDist -Destination $legacyVicRoadsDist
}
if (Test-Path -LiteralPath $finesVicDist) {
  Sync-Directory -Source $finesVicDist -Destination $legacyFinesVicDist
}

if (Test-Path -LiteralPath $outputRoot) {
  Write-Host "==> Removing existing output: $outputRoot" -ForegroundColor Yellow
  Remove-Item -LiteralPath $outputRoot -Recurse -Force
}
[System.IO.Directory]::CreateDirectory($outputRoot) | Out-Null

Sync-Directory -Source $cadBridgeSource -Destination (Join-Path $outputRoot 'cad_bridge')
Sync-Directory -Source $vicroadsSource -Destination (Join-Path $outputRoot 'npwd_vicroads') -ExcludeDirectories @('node_modules')
Sync-Directory -Source $finesVicSource -Destination (Join-Path $outputRoot 'npwd_fines_victoria') -ExcludeDirectories @('node_modules')

$readme = @"
QuokkaCAD FiveM Resource Pack
=============================

This folder is generated by:
  deploy/scripts/package-quokkacad.ps1

Resources included:
  - cad_bridge
  - npwd_vicroads
  - npwd_fines_victoria

Server.cfg example:
  ensure npwd
  ensure [quokkacad]

NPWD app config must include:
  "apps": [
    "npwd_vicroads",
    "npwd_fines_victoria"
  ]

Rebuild this pack after changing cad_bridge or either NPWD app.
"@
[System.IO.File]::WriteAllText((Join-Path $outputRoot 'README.txt'), $readme, [System.Text.Encoding]::UTF8)

Write-Host "`nPackaged resources into: $outputRoot" -ForegroundColor Green
Get-ChildItem -LiteralPath $outputRoot -Directory | Select-Object Name, FullName | Format-Table -AutoSize
